version: '3.8'

volumes:
  static:
  media:

services:

  django:
    build:
      context: .
    ports:
      - '8000:8000'
    container_name: djangostripe
    env_file:
      - .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    command: sh -c "python manage.py collectstatic --no-input &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"